### PR TITLE
Update controls-exposer.js to new interfaces

### LINKED ISSUE #9: Error after updating to 1.40.0
After updating to the latest version on my HA instance the script stopped working and I am getting the following error:

```
error 2024-09-01 22:46:23z2m: Failed to call 'MiboxerFut089zControlsExposer' 'start' (TypeError: this.zigbee.devices is not a function at MiboxerFut089zControlsExposer._getAvailableMiBoxerRemotes (/app/data/extension/Remote-script-2.js:132:28) at MiboxerFut089zControlsExposer.start (/app/data/extension/Remote-script-2.js:136:37) at Controller.callExtensions (/app/lib/controller.ts:377:42) at Controller.addExtension (/app/lib/controller.ts:236:20) at ExternalExtension.loadExtension (/app/lib/extension/externalExtension.ts:95:20) at processTicksAndRejections (node:internal/process/task_queues:95:5) at ExternalExtension.saveExtension (/app/lib/extension/externalExtension.ts:64:9) at ExternalExtension.onMQTTMessage (/app/lib/extension/externalExtension.ts:82:34) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))
```

### PR DESCRIPTION
**Pull request by daxcore**
.FIXES #9

### CODE REVIEW

**Comment by Koenkk** [comment]
Thanks!
