### ISSUE TITLE
Error after updating to 1.40.0

### ISSUE THREAD

**Issue by Luk164** [Koenkk/zigbee2mqtt-user-extensions#9]
After updating to the latest version on my HA instance the script stopped working and I am getting the following error:

```
error 2024-09-01 22:46:23z2m: Failed to call 'MiboxerFut089zControlsExposer' 'start' (TypeError: this.zigbee.devices is not a function at MiboxerFut089zControlsExposer._getAvailableMiBoxerRemotes (/app/data/extension/Remote-script-2.js:132:28) at MiboxerFut089zControlsExposer.start (/app/data/extension/Remote-script-2.js:136:37) at Controller.callExtensions (/app/lib/controller.ts:377:42) at Controller.addExtension (/app/lib/controller.ts:236:20) at ExternalExtension.loadExtension (/app/lib/extension/externalExtension.ts:95:20) at processTicksAndRejections (node:internal/process/task_queues:95:5) at ExternalExtension.saveExtension (/app/lib/extension/externalExtension.ts:64:9) at ExternalExtension.onMQTTMessage (/app/lib/extension/externalExtension.ts:82:34) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))
```

**Comment by rsilvestre** [comment]
Same issue

**Comment by lexeyt** [comment]
Same problem. Any ideas on how to fix this?

**Comment by daxcore** [comment]
hi there. 

i'm not the master of javascript development, but I guess I fixed the issues, because of changed interfaces:

```diff
diff controls-exposer1.js controls-exposer2.js -u
--- controls-exposer1.js	2024-10-02 22:26:29
+++ controls-exposer2.js	2024-10-02 22:26:46
@@ -4,7 +4,7 @@
  * This extension registers and exposes the remote's controls, making them available on the appropriate MQTT topics.
  */
 const DISCOVERY_PREFIX = 'homeassistant';
-const VERSION = "1.0.1-unstable";
+const VERSION = "1.0.2-unstable";
 const NAME = "miboxer-fut089z/controls-exposer";
 
 class MiboxerFut089zControlsExposer {
@@ -24,7 +24,7 @@
     
     _setupDeviceDiscovery(device) {
         const ieeeAddr = device.zh._ieeeAddr;
-        const { vendor, model, description } = device._definition;
+        const { vendor, model, description } = device.definition;
     
         // Set up discovery for the buttons:
         for (const buttonType of ['on', 'off']) {
@@ -125,18 +125,16 @@
     }
     
     _deviceIsSupportedRemote(device) {
-        return device?._definition?.vendor === 'MiBoxer' && device?._definition?.model === 'FUT089Z'
+        return device?.definition?.vendor === 'MiBoxer' && device?.definition?.model === 'FUT089Z';
     }
     
-    _getAvailableMiBoxerRemotes() {
-        return this.zigbee.devices().filter(device=>this._deviceIsSupportedRemote(device));
-    }
-    
-    start() {
-        const miBoxerRemotes = this._getAvailableMiBoxerRemotes() || [];
-        
+    start() {        
         // Setup discovery for remotes that have been added before the extension was started
-        miBoxerRemotes.forEach(device => this._setupDeviceDiscovery(device));
+        for (const device of this.zigbee.devicesIterator()) {
+            if (this._deviceIsSupportedRemote(device)) {
+                this._setupDeviceDiscovery(device);
+            }
+        }
         
         // Setup discovery for remotes that are added while the extension is running
         this.eventBus.onDeviceAnnounce(this, (data) => { // TODO: Research if onDeviceJoined is necessary as well
@@ -149,7 +147,7 @@
         // Listen for events fired by the remote(s)
         this.eventBus.onDeviceMessage(this, (data) => {
             try {
-            const { vendor, model } = data.device._definition;
+            const { vendor, model } = data.device.definition;
             if (vendor === 'MiBoxer' && model === 'FUT089Z') {
                 const ieeeAddr = data.device.zh._ieeeAddr;
                 const { type, groupID, cluster } = data;
```

also opened a pull-request: https://github.com/Koenkk/zigbee2mqtt-user-extensions/pull/10

**Comment by daxcore** [comment]
update, also the fixed script (including color) doesn't make the full functionality available of the remote control. now I use mqtt directly. that works very well for me.

```
alias: test automation
description: ""
trigger:
  - platform: mqtt
    topic: zigbee2mqtt/0xf082c0fffeb174ef
condition: []
action:
  - variables:
      mylight: light.0xa81710b98bb20000
  - if:
      - condition: template
        value_template: "{{ trigger.payload_json.action_group == 101 }}"
    then:
      - if:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'move_to_hue_and_saturation' }}"
        then:
          - action: light.turn_on
            data:
              hs_color:
                - "{{ trigger.payload_json.action_hue*360/254 }}"
                - "{{ (trigger.payload_json.action_saturation-170)/84*100 }}"
            target:
              entity_id: "{{ mylight }}"
      - if:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'brightness_move_to_level' }}"
        then:
          - action: light.turn_on
            data:
              brightness: "{{ trigger.payload_json.action_level }}"
            target:
              entity_id: "{{ mylight }}"
      - if:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'color_temperature_move' }}"
        then:
          - action: light.turn_on
            data:
              color_temp: "{{ trigger.payload_json.action_color_temperature }}"
            target:
              entity_id: "{{ mylight }}"
      - if:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'on' }}"
        then:
          - action: light.turn_on
            target:
              entity_id: "{{ mylight }}"
      - if:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'off' }}"
        then:
          - action: light.turn_off
            target:
              entity_id: "{{ mylight }}"
mode: single
```
Just replace mqtt `topic`and `mylight`variable.
